[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.78.0",
    "pandas>=2.2.3",
    "requests>=2.32.3",
    "streamlit>=1.45.0",
]
